### ISSUE TITLE
Benchmark Datasets (too) Flawed 

### ISSUE THREAD

**Issue by jaymefosa** [signals-dev/Orion#122]
https://www.reddit.com/r/MachineLearning/comments/j2cqa2/r_current_time_series_anomaly_detection/

Above is a link to a discussion around a paper highlighting issues in NASA, NAB, and Yahoo datasets. 

The paper itself has some distracting framing issues but raises excellent points in the benchmark datasets. 

Highly recommend effort is made towards resolving the ground truth errors.

**Comment by sarahmish** [comment]
Thanks @jaymefosa.

We can move the discussions about datasets into their separate issues #117 and #116.
Closing this for now.
