### ISSUE TITLE
tadGAN is not detecting benchmark anomaly

### ISSUE THREAD

**Issue by JINU8** [signals-dev/Orion#127]
[tdgan.zip](https://github.com/signals-dev/Orion/files/5382876/tdgan.zip)
* Orion version:
* Python version:
* Operating System:

### Description
I am trying to use TadGAN pipeline; on 'nyc_taxi' datasets. But its not detecting the benchmark known anomalies as expected 

### What I Did
```
signal = 'nyc_taxi'
df = load_signal(signal)
orion = Orion(pipeline='tadgan')
anomalies =orion.fit_detect(df)


```
I get this warning error and also anomaly is not rightly detected. 
```

error:
/usr/local/lib/python3.6/dist-packages/scipy/optimize/optimize.py:700: RuntimeWarning: invalid value encountered in subtract
  np.max(np.abs(fsim[0] - fsim[1:])) <= fatol):

**Comment by sarahmish** [comment]
Hi @JINU8, there is a bit of configuration needed for the `nyc_taxi` dataset that are not available in the default pipeline. You can use the hyperparameter settings to denote these changes as follows:

```python3
from orion.data import load_signal
from orion import Orion

signal = 'nyc_taxi'
df = load_signal(signal)

hyperparameter = {
    "mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1": {
        "interval": 1800 # 30 minute level
    },
    "orion.primitives.timeseries_anomalies.find_anomalies#1": {
        "window_size_portion": 0.33,
        "window_step_size_portion": 0.1,
        "fixed_threshold": true
    }
}

orion = Orion(
    'tadgan',
    hyperparameter
)

anomalies = orion.fit_detect(df)
```
The randomized nature of `tadgan` will not guarantee that you get the exact same anomalies in each run, but they should be comparable.

To read more about the `tadgan` pipeline, we've written a blogpost that explains the series of transformations [here](https://link.medium.com/5GrTDzfjCab).
