### ISSUE TITLE
support for multivariate time series

### ISSUE THREAD

**Issue by geoHeil** [signals-dev/Orion#141]
According to the documentation, only univariate time series are supported.

However, in the IEEE TadGan publication, you write that multivariate time series (in principle) should be supported.
If this is true - how can I use multivariate time series with Orion?

**Comment by sarahmish** [comment]
Hi @geoHeil.

You are right. In theory, TadGAN is able to work on multivariate time series. Though, Orion as a framework is standardized on the input being univariate and that is what we currently support. 

If you wish to further investigate TadGAN on multivariate time series, you can explore its implementation externally [here](https://github.com/signals-dev/Orion/blob/master/orion/primitives/tadgan.py). In this case, the relative input/output dimensions will be changed. 

Hope this answers your question

**Comment by geoHeil** [comment]
thx
