### ISSUE TITLE
ValueError: Unknown pipeline: tadgan.json

### ISSUE THREAD

**Issue by Shanginre** [signals-dev/Orion#152]
* 0.1.5:
* Python version: 3.6.2 64 bit (AMD64)
* Operating System: Windows 64

### Description

when I try to create an Orion object I get the error:
`orion = Orion (pipeline = 'tadgan.json')`

sample code took from [here](https://medium.com/mit-data-to-ai-lab/time-series-anomaly-detection-in-the-era-of-deep-learning-f0237902224a)

although creating an Orion object with such parameters does not give an error
`orion = Orion (pipeline = 'tadgan')`

where I get a strange warning:

> WARNING: tensorflow: From C: PycharmProjects \ test_orion \ venv \ lib \ site-packages \ tensorflow_core \ python \ ops \ resource_variable_ops.py: 1630: calling BaseResourceVariable .__ init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
> Instructions for updating:
> If using Keras pass * _constraint arguments to layers.

**Where can I find a comprehensive up-to-date guide to the library API?**

**And another question: is the library production ready? Errors like these raise doubts about it.**

**Comment by sarahmish** [comment]
Hi @Shanginre!

**Loading tagan**
In the tulog code (medium post), we have a dedicated folder that contains the `tadgan.json` which you can find [here](https://github.com/signals-dev/Orion/tree/master/notebooks/tulog). You can dump the `tadgan.json` into your working directory and it should run smoothly from there. Or alternatively give your path to the `json` file `orion = Orion(pipeline='/path/to/tadgan.json')`.

It is not different from using `orion = Orion(pipeline='tadgan')` except that the hyperparameter settings are different. In this case, you are running the pipeline maintained in the repo [here](https://github.com/signals-dev/Orion/blob/master/orion/pipelines/verified/tadgan/tadgan.json).

**Guides**
We're working on the documentation of this library extensively right now. You can see the latest documentation here: https://signals-dev.github.io/Orion/. You can find our user guides and API references there as well.

**Warnings**
The warnings you see can be safely ignored as they do not interfere with the proper behavior of the pipeline. The pipeline will produce the desired output. I also want to emphasize that this is a maintained repo and we're continuously updating it. If you have any trouble, please don't hesitate to raise an issue and reach out

I hope this addresses your concerns, let me know if you have any further questions!
