### ISSUE TITLE
Inaccuracy in README.md file in orion/evaluation/

### ISSUE THREAD

**Issue by Shanginre** [signals-dev/Orion#157]
* Orion version: 0.1.5
* Python version: 3.6.2 64 бит (AMD64)
* Operating System: Windows 64

### Description

perhaps **weighted = False**, as in the [manual](https://signals-dev.github.io/Orion/user_guides/evaluation_doc.html)

![image](https://user-images.githubusercontent.com/11506233/104393938-6508cc80-5567-11eb-9bb8-035613d33ee2.png)

**Comment by sarahmish** [comment]
Thanks for pointing this out @Shanginre!

I will update it shortly
