### ISSUE TITLE
Trouble with the installation under Ubuntu 18.4: skbuild and cmake missing in requirements?

### ISSUE THREAD

**Issue by JanWaldhorn** [signals-dev/Orion#164]
* Orion version: v0.1.5 - 2020-12-25
* Python version: 3.6.9
* Operating System: Ubuntu 18.04 as VM

### Description

I wanted to try orion and have (clean) installed ubuntu as a VM under win 10 as host system.
I basically just installed `pip3 `and `python3-venv` before running `pip install orion-ml`.

### What I Did
After the installation command with pip `pip install orion-ml` comes some normal output until
```
    ModuleNotFoundError: No module named 'skbuild'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-z08yvoj5/opencv-python/
```
So I had to install scikit manually `pip install scikit-build`

Another attempt ended with the missing of cmake

```

Problem with the CMake installation, aborting build. CMake executable is cmake

----------------------------------------
Failed building wheel for opencv-python
```

I was able to fix this via `sudo apt  install cmake`.

Maybe it would be possible to catch such error sources in the requirements? As far as I could see, I am the first with such errors, which surprises me a bit. But maybe it helps to improve it.

Thanks for your work!

**Comment by sarahmish** [comment]
Hi @JanWaldhorn! 

Try upgrading pip first `pip install --upgrade pip` then installing orion `pip install orion-ml`. It should fix the problem.

Reason being,  opencv has pre-built wheels which is supported only by `pip>=19.3`.

**Comment by JanWaldhorn** [comment]
Hi @sarahmish, thank you for the reply. Indeed pip in version 9.0.1 is a bit old. Maybe this could be caught in requirements (as a warning)?

**Comment by sarahmish** [comment]
Typically a pip warning message will appear when you are using an old pip. something close to `WARNING: You are using pip version 9.0.1; however, version 21.0 is available`.

More information about this issue (`opencv-python` installation) can be found here https://github.com/opencv/opencv-python#frequently-asked-questions
