### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by alnethary** [signals-dev/Orion#165]
I have a question regarding TADGAN!
When running TADGAN for some iteration, I got results similar to :
Epoch: 1/70, [Dx loss: [-1.5523657  -7.363176    0.53680336  0.52740085]] [Dz loss: [ 1.7724311  -0.15395202  1.1521084   0.07742747]] [G loss: [ 7.1117606  -0.71072316 -1.0893183   0.8911803 ]]
Epoch: 2/70, [Dx loss: [ -9.296486  -13.59008     2.6210668   0.1672527]] [Dz loss: [-0.70878696 -0.783488   -0.29704252  0.03717436]] [G loss: [ 3.5069776 -2.707703   3.210976   0.3003705]]
.....

Why there are four losses for the  DX, Dz and G in each iteration. I was expected to see only one loss for each.
@sarahmish , any explanation?
Thanks

**Comment by alnethary** [comment]
I've just seen the answer for my question in issue 160, thanks

**Comment by nunobv** [comment]
just reviving this post to address some doubts of mine:

- how can the `eg_loss` be negative? i have some occurences during training and reading the paper i could not find an explanation for this.
- a good model should see the `eg_loss` minimized while the `cx_loss` increasing during the training epochs, right?
- i don't have a good sense to what `cz_loss` should be, but i suspect it should oscillate around 0?
