### ISSUE TITLE
Question: Can Orion be used for multiple streams detection?

### ISSUE THREAD

**Issue by AKJHK2021** [signals-dev/Orion#166]
### Description

In the paper it says that TadGAN can be used for multiple signals detection. However, looking at the Orion/TadGAN class and the preprocessing functions, it doesn't seem that can be done trivially. I might be wrong..

**Comment by kb1ooo** [comment]
See issue #141  I would love general support for multivariate signals.

**Comment by A2015Albasir** [comment]
@kb1ooo, the heavy dependency on other packages, such as MLBlocks and MLPipelines, made the contribution to the to this particular feature be very difficult, at least to me...

**Comment by kb1ooo** [comment]
@AKJHK2021 I understand, I just think that semi-supervised anomaly detection is a hard problem and in most applications, multiple measurements are available.  Leveraging these in a way that goes beyond separate models for each signal and post prediction fusion would likely boost prediction accuracy.

**Comment by sarahmish** [comment]
Hi @AKJHK2021

As @kb1ooo has mentioned, the current support is for univariate timeseries.
