### ISSUE TITLE
not able to install it in Anaconda.

### ISSUE THREAD

**Issue by RaunakKumarVerma** [signals-dev/Orion#170]
* Orion version: Not able to install
* Python version:3.8.5
* Operating System: Microsoft Windows 10 version 20H2( OS Build 19042.746)

### Description
I Tried installing this into my anaconda env for my college project but its not installing. Can you please help me solve the problem?

Tell us what happened, what went wrong, and what you expected to happen.

### What I Did
(ProjectGAn) C:\Users\Raunak>pip install orion-ml
Collecting orion-ml
  Using cached orion_ml-0.1.0-py2.py3-none-any.whl (38 kB)
Collecting baytune<0.3,>=0.2.3
  Using cached baytune-0.2.5-py2.py3-none-any.whl (28 kB)
Requirement already satisfied: six>=1.0 in c:\users\raunak\.conda\envs\projectgan\lib\site-packages (from baytune<0.3,>=0.2.3->orion-ml) (1.15.0)
Requirement already satisfied: scipy>=1.0.1 in c:\users\raunak\.conda\envs\projectgan\lib\site-packages (from baytune<0.3,>=0.2.3->orion-ml) (1.6.0)
Collecting mlblocks<0.4,>=0.3.0
  Using cached mlblocks-0.3.4-py2.py3-none-any.whl (26 kB)
Collecting mlprimitives<0.3,>=0.2.2
  Using cached mlprimitives-0.2.4-py2.py3-none-any.whl (179 kB)
Requirement already satisfied: Keras<3,>=2.1.6 in c:\users\raunak\.conda\envs\projectgan\lib\site-packages (from mlprimitives<0.3,>=0.2.2->orion-ml) (2.4.3)
  Using cached mlprimitives-0.2.3-py2.py3-none-any.whl (177 kB)
  Using cached mlprimitives-0.2.2-py2.py3-none-any.whl (161 kB)
INFO: pip is looking at multiple versions of mlblocks to determine which version is compatible with other requirements. This could take a while.
Collecting mlblocks<0.4,>=0.3.0
  Using cached mlblocks-0.3.3-py2.py3-none-any.whl (26 kB)
  Using cached mlblocks-0.3.2-py2.py3-none-any.whl (25 kB)
  Using cached mlblocks-0.3.1-py2.py3-none-any.whl (23 kB)
  Using cached mlblocks-0.3.0-py2.py3-none-any.whl (19 kB)
INFO: pip is looking at multiple versions of baytune to determine which version is compatible with other requirements. This could take a while.
Collecting baytune<0.3,>=0.2.3
  Using cached baytune-0.2.4-py2.py3-none-any.whl (27 kB)
INFO: pip is looking at multiple versions of mlblocks to determine which version is compatible with other requirements. This could take a while.
  Using cached baytune-0.2.3-py2.py3-none-any.whl (27 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of orion-ml to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install orion-ml because these package versions have conflicting dependencies.

The conflict is caused by:
    mlprimitives 0.2.4 depends on tensorflow<2 and >=1.11.0
    mlprimitives 0.2.3 depends on tensorflow<2 and >=1.11.0
    mlprimitives 0.2.2 depends on tensorflow<2 and >=1.11.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
Describe what you were trying to get done.

**Comment by sarahmish** [comment]
Hi @RaunakKumarVerma!

At the moment, we're not supporting python 3.8. Can you try it using python 3.6 or 3.7? I recommend creating a new conda environment then installing orion.

```
conda create -n orion python=3.7
conda activate orion
pip install orion-ml
```

Let me know if this solves your issue
