### ISSUE TITLE
Train/Test Split

### ISSUE THREAD

**Issue by salman087** [signals-dev/Orion#173]
I can't see the data is divided into train/test. It seems like the data is not divided into train or test and if done what is its percentage.

**Comment by salman087** [comment]
I can't see the data is divided into train/test. It seems like the data is not divided into train or test and if done what is its percentage.

**Comment by sarahmish** [comment]
Hi @salman087!

In the _quickstart_, we use a predefined train/test split. 
```python3
train_data = load_signal('S-1-train') # for training
new_data = load_signal('S-1-new') # for testing
```
note that `train_data` and `new_data` do not overlap.

However, you can split your signal using `train_data, test_data = load_signal('S-1', test_size=0.2)`.
