### ISSUE TITLE
bullet points not formatted correctly in index.rst

### ISSUE THREAD

**Issue by micahjsmith** [signals-dev/Orion#178]
See https://github.com/signals-dev/Orion/blob/master/docs/index.rst#unsupervised-time-series-anomaly-detection-utsad

Need a line break before the bullet points in rST

**Comment by micahjsmith** [comment]
hi @sarahmish, for the assignment of myself to this issue, do I need to do anything else?

**Comment by sarahmish** [comment]
The assignment was in preparation for a new release. I am just making sure all issues are properly labeled and assigned. Nothing further is required @micahjsmith 🙂
