### ISSUE TITLE
Issue with installing

### ISSUE THREAD

**Issue by etsi123** [signals-dev/Orion#193]
The recommended method for installing orion-ml is via pip (e.g., pip install orion-ml) as stated in the github README.md

However, this simple command causes the error

    INFO: pip is looking at multiple versions of baytune to determine which version is 
    compatible with other requirements. This could take a while.  
    Collecting baytune<0.3,>=0.2.3
      Using cached baytune-0.2.4-py2.py3-none-any.whl (27 kB)
      Using cached baytune-0.2.3-py2.py3-none-any.whl (27 kB)
    INFO: pip is looking at multiple versions of mlblocks to determine which version is 
    compatible with other requirements. This could take a while.
    INFO: This is taking longer than usual. You might need to provide the dependency resolver 
    with stricter constraints to reduce runtime. If you want to abort this run, you can press 
    Ctrl + C to do so. To improve how pip performs, tell us what happened here: 
    https://pip.pypa.io/surveys/backtracking
    INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine 
    which version is compatible with other requirements. This could take a while.
    INFO: pip is looking at multiple versions of orion-ml to determine which version is 
    compatible with other requirements. This could take a while.
    ERROR: Cannot install orion-ml because these package versions have conflicting dependencies.
    
    The conflict is caused by:
        mlprimitives 0.2.4 depends on tensorflow<2 and >=1.11.0
        mlprimitives 0.2.3 depends on tensorflow<2 and >=1.11.0
        mlprimitives 0.2.2 depends on tensorflow<2 and >=1.11.0

    To fix this you could try to:
    1. loosen the range of package versions you've specified
    2. remove package versions to allow pip attempt to solve the dependency conflict
    
    ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

This tells us there is a version conflict. How can I resolve this? Thank you

**Comment by sarahmish** [comment]
hi @etsi123!

Would you mind installing `orion-ml` in a separate environment? I'm suspecting that there is a conflict here between `mlprimitives` and the pre-installed version of `tensorflow` and that's why pip cannot resolve it.

you can create a conda env like so
```
conda create --name orion python=3.7
conda activate orion
```
or using virtualenv
```
python3 -m venv orion
source orion/bin/activate
```

If you do not wish to use another environment, would you ensure that the `tensorflow` version you are using is between 1.11 and less than 2?
