### ISSUE TITLE
GPU and Orion

### ISSUE THREAD

**Issue by kioja-stack** [signals-dev/Orion#203]
Hi, I want to know if Orion is compatible with GPU. Because I tried to run my code on CPU it worked properly, but when I want to use GPU it is not possible to use it. Could you please give a hint or guidance in this regard.

Thanks

**Comment by sarahmish** [comment]
Hi @kioja-stack!

To use GPU pipelines, append the pipeline name with `_gpu`. Example code below:
```python3
from orion import Orion

orion = Orion(
    pipeline='lstm_dynamic_threshold_gpu',
)
```
As of now, we only support GPU versions of `lstm_dynamic_threshold` and `tadgan` pipelines.

The GPU pipelines use `CuDNNLSTM` layers, make sure you have a compatible version installed of `CuDA` and `tensorflow-gpu` to run successfully. You can find more about possible configurations in TF [documentation](https://www.tensorflow.org/install/source#linux).

**Comment by Huilin-Zhu** [comment]
Hi, what if tadgan model is loaded directly from primitives instead of pipeline: 

`tadgan = load_primitive('orion.primitives.tadgan.TadGAN')`
`tadgan.fit()`

Is there a way to run the model on GPU? Thanks in advance!

**Comment by cjtaylo-csu** [comment]
OS Version: Ubuntu 18.04.5
Tensorflow/tensorflow-gpu Version: 1.14.0
Python version: 3.6.13
Cuda version: 11.5
 
Hello,

What is the correct version of tensorflow/tensorflow-gpu to be used?
I changed the pipeline in the tulog experiment to:

```
orion = Orion(
    pipeline='../../orion/pipelines/verified/tadgan/tadgan_gpu.json'
)
```

But when using tensorflow-gpu 1.14.0 I get the following error:

`DistributionNotFound: The 'tensorflow<2,>=1.11.0' distribution was not found and is required by the application`

The following command sees my GPU:
```
from tensorflow.python.client import device_lib
device_lib.list_local_devices()
```

Using tensorflow 1.14.0 results in the following error:
`No registered kernels`, and the command above does not see my GPU.

PS: I tried to run in the docker environment but upon running the notebooks/tulog tutorial it crashed saying:

`PermissionError: [Errno 13] Permission denied: '/app/orion/data/'`

Thank you for your help. I am really hoping to use tadgan with my GPU

**Comment by cjtaylo-csu** [comment]
Hello @sarahmish,

I am trying to do as @Huilin-Zhu was attempting:
Run the tadGAN model with a GPU using the primitives, rather than the full pipeline like the second part of the tulog example notebook.

I added the hyper parameters for *layers_encoder* and *layers_generator* from the tadgan_gpu pipeline. Then started the training with `tgan.fit(X)`.  Below is my modified code cell 14:

```
from model import hyperparameters
from orion.primitives.tadgan import TadGAN

hyperparameters["epochs"] = 5
hyperparameters["input_shape"] = (100, 1) # based on the window size
hyperparameters["optimizer"] = "keras.optimizers.Adam"
hyperparameters["learning_rate"] = 0.0005
hyperparameters["latent_dim"] = 20
hyperparameters["batch_size"] = 64
hyperparameters["layers_encoder"] = [
                {
                    "class": "keras.layers.Bidirectional",
                    "parameters": {
                        "layer": {
                            "class": "keras.layers.CuDNNLSTM",
                            "parameters": {
                                "units": 100,
                                "return_sequences": True
                            }
                        }
                    }
                },
                {
                    "class": "keras.layers.Flatten",
                    "parameters": {}
                },
                {
                    "class": "keras.layers.Dense",
                    "parameters": {
                        "units": 20
                    }
                },
                {
                    "class": "keras.layers.Reshape",
                    "parameters": {
                        "target_shape": "encoder_reshape_shape"
                    }
                }
            ]
hyperparameters["layers_generator"] = [
                    {
                        "class": "keras.layers.Flatten",
                        "parameters": {}
                    },
                    {
                        "class": "keras.layers.Dense",
                        "parameters": {
                            "units": 50
                        }
                    },
                    {
                        "class": "keras.layers.Reshape",
                        "parameters": {
                            "target_shape": "generator_reshape_shape"
                        }
                    },
                    {
                        "class": "keras.layers.Bidirectional",
                        "parameters": {
                            "layer": {
                                "class": "keras.layers.CuDNNLSTM",
                                "parameters": {
                                    "units": 64,
                                    "return_sequences": True
                                }
                            },
                            "merge_mode": "concat"
                        }
                    },
                    {
                        "class": "keras.layers.convolutional.UpSampling1D",
                        "parameters": {
                            "size": 2
                        }
                    },
                    {
                        "class": "keras.layers.Bidirectional",
                        "parameters": {
                            "layer": {
                                "class": "keras.layers.CuDNNLSTM",
                                "parameters": {
                                    "units": 64,
                                    "return_sequences": True
                                }
                            },
                            "merge_mode": "concat"
                        }
                    },
                    {
                        "class": "keras.layers.TimeDistributed",
                        "parameters": {
                            "layer": {
                                "class": "keras.layers.Dense",
                                "parameters": {
                                    "units": 1
                                }
                            }
                        }
                    },
                    {
                        "class": "keras.layers.Activation",
                        "parameters": {
                            "activation": "tanh"
                        }
                    }
            ]


tgan = TadGAN(**hyperparameters)
tgan.fit(X)
```


I can see my GPU is being utilized, but the 35 epochs of training is significantly slower than using the *tadgan_gpu* pipeline. I suspect something is being offloaded to the CPU. I diff'ed the tadgan.json and tadgan_gpu.json files and saw only the two layers as being the significant changes from the default hyperparameters.

Are there any other obvious pieces missing in order to run a primitive based tadGAN on a GPU?

I'd be happy to add a tulog_gpu notebook if I can get this working. I think others may benefit.

Thank you
