### ISSUE TITLE
Save and Load the model

### ISSUE THREAD

**Issue by kioja-stack** [signals-dev/Orion#206]
* Orion version: 0.1.5
* Python version: 3.7.10
* Operating System: Win 10

Hi, I used following code to train my TadGAN:

from model import hyperparameters
from orion.primitives.tadgan import TadGAN

hyperparameters["epochs"] = 35
hyperparameters["shape"] = (100, 1) # based on the window size
hyperparameters["optimizer"] = "keras.optimizers.Adam"
hyperparameters["learning_rate"] = 0.0005
hyperparameters["latent_dim"] = 20
hyperparameters["batch_size"] = 64

tgan = TadGAN(**hyperparameters)
tgan.fit(X)

I need to save the trained model in order to use it later. Could you please guide me and tell me, what are the commands to save and load the trained model? Thanks in advance.

**Comment by sarahmish** [comment]
Hi @kioja-stack!

This is something that we recently addressed in Issue #200. 
Thus, please upgrade the package to the latest version first `pip install -U orion-ml` or `pip install orion-ml==0.1.6`. Then, you can simply pickle `tgan` directly.

```python3
import pickle

# save model
with open("model.pkl", "wb") as pickle_file:
    pickle.dump(tgan, pickle_file)

# load model
with open("model.pkl", "rb") as pickle_file:
    tgan = pickle.load(pickle_file)
```
**Note** you can use `tgan` later for predictions but you will not be able to continue training it (i.e. `tgan.fit` will raise an error). This is another issue that I am currently working.

**Comment by kioja-stack** [comment]
Hi @sarahmish,

Thank you so much for the information. I am really sorry I didn't notice that issue. Again thanks alot :)

**Comment by sarahmish** [comment]
Happy to help! I mentioned the issue as a reference, you did not have to go through it 😄 

Closing since the issue has been resolved

**Comment by kioja-stack** [comment]
Hi @sarahmish ,

Thanks for your supports :)

I upgraded my orion version to 0.1.6 and used the code you gave me above. Unfortuantely, when I want to save the model, I receive the following error.

![image](https://user-images.githubusercontent.com/80001550/110552177-d8146680-8104-11eb-81df-f19c24b49a17.png)

I tried to give a specific address to save the pickel file, but it is not the case. As my pickle file name is something different from the one given in the error.

**Comment by sarahmish** [comment]
Thanks for the feedback @kioja-stack. I will re-open this issue until you can confirm that this problem is resolved!

Can you try changing the configuration of `tempfile` to a directory with read/write permissions?
```python3
import tempfile

tempfile.tempdir = # folder path
```
Then try to pickle the model. If this doesn't work can you please run `tempfile.gettempdir()` and let me know what does it return?

**Comment by sarahmish** [comment]
Can you confirm that you can read/write to the folder from a python shell? 
I'm wondering if it will raise the same issue
```python3
open("path/to/folder/")
```
 
If that's the case, it seems like a compatibility issue, can you paste the entire error output? It will help me trace the problem

**Comment by kioja-stack** [comment]
Hi @sarahmish,

I tested what you said and this is the result.

![image](https://user-images.githubusercontent.com/80001550/110849786-467c3480-827d-11eb-925c-852a0ed7aefd.png)

**Comment by sarahmish** [comment]
I have my suspicion that we are not properly setting the path. Normally, I would run my tests locally to figure out the issue but since this is case specific to you, I appreciate the time you are taking to run the experiments.

I configured `tempfile` to the current working directory (which I assume you have permissions to)
```python3
import tempfile 
import pickle
import os 

tempfile.tempdir = os.getcwd()

# sanity check 1 
print(tempfile.gettempdir()) # this should return your current working directory

# sanity check 2
with tempfile.TemporaryFile() as fp: 
    fp.write(b'Hello world!')
```
Does the above code run without a problem?

**Comment by kioja-stack** [comment]
Hi again. No problem. My pleasure :)

I ran this code and it works without any error

**Comment by sarahmish** [comment]
Perfect! Try saving your `tgan` model given this edit

```python3
import tempfile 
import pickle
import os 

tempfile.tempdir = os.getcwd()

with open("model.pkl", "wb") as pickle_file:
    pickle.dump(tgan, pickle_file)
```

It should work now

**Comment by kioja-stack** [comment]
Hi again @sarahmish ,

No it didn't work. This is the full error message.

![image](https://user-images.githubusercontent.com/80001550/110896682-173fe480-82ca-11eb-83d2-89afea420bca.png)

**Comment by sarahmish** [comment]
I see, it's a permissions issue on your system. 

To confirm the problem, you can try to use `h5py` for writing/reading. For example
```python3
import h5py
import numpy as np

f = h5py.File("mytestfile.hdf5", "w")
```


I think the read/write privileges are not granted to `os` (web server) which is causing `h5py` to raise an error. There are two approaches that I can see working:

**1. Grant permission to the web server**
you can read about a similar problem here: https://stackoverflow.com/questions/41910583/errno-13-permission-denied-python/52452024

**2. Install `orion` on user folder**
you can do this by `pip install orion-ml --user` and then it should have the same permissions as the user. Remember to first uninstall the global version `pip uninstall orion-ml`

Hopefully one of these two approaches work

**Comment by kioja-stack** [comment]
Hi @sarahmish 

I ran the code as you sent. It works without any problem.

Also I uninstalled the global version of orion-ml and installed it for the user. But again I received the same error.

**Comment by sarahmish** [comment]
Hi @kioja-stack, just to confirm you tried option 2 and it did not work, correct?

I will experiment with this problem on window and see if I can pinpoint the issue. It might take me a while, I appreciate your patience

**Comment by kioja-stack** [comment]
Hi @sarahmish ,

Yes, I tried option 2 and it didn't work. Thank you so much

**Comment by sarahmish** [comment]
Hi @kioja-stack,

Thanks for your patience. I made PR #216 to fix your issue and it should be good to go.

To reflect the most recent changes, you need to install orion from [source](https://signals-dev.github.io/Orion/getting_started/install.html#install-from-source), or wait till the next version is available on pip.

**Comment by kioja-stack** [comment]
Hi @sarahmish,

Thank you so much :)

**Comment by ajthomas1949** [comment]
When using pickle to save a model, I get the warning:
 /usr/local/lib/python3.7/dist-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually. warnings.warn('No training configuration found in save file: '

I am able to reload the model from the pickle file and find anomalies. Is this message significant? If so, how to
avoid it?

Thanks!
