### ISSUE TITLE
No able to modify Tadgan Hyperparameters

### ISSUE THREAD

**Issue by GiacomoSintoni** [signals-dev/Orion#209]
* Orion version: orion-ml 0.1.6
* Python version: Python 3.6.8
* Operating System: Windows

### Description
I encountered some problems after hyperparameters changing.
For example when I modify some parameters such as the "window_size" of the rolling Windows, the step_size, or other parameters throw the TadGAN.json file, the process stops suddenly for example after a strange behaviour:

![image](https://user-images.githubusercontent.com/75069381/110653868-ed999700-81bd-11eb-81c8-7ec801cb73fd.png)

So I can’t change default parameters.
If I use perfectly your default parameters all works. But I want to use my own ones. Can you help me to fix this issue?

In particular, a matching error occur also if I change manually the hyperparameters from the model.py file:

![image](https://user-images.githubusercontent.com/75069381/110655218-2423e180-81bf-11eb-882a-40103515ff35.png)

### What I Did

For example:
I changed "window_size" parameter in "rolling_window_sequences" function from 100 to 200. 
![image](https://user-images.githubusercontent.com/75069381/110656607-626dd080-81c0-11eb-8d98-c88aaf85f551.png)

After that, I changed the hyperparameters in the model.py file, like "shape" from 100 to 200:
![image](https://user-images.githubusercontent.com/75069381/110656746-86c9ad00-81c0-11eb-87a2-75485cbeb7fd.png)

And I ran this:
![image](https://user-images.githubusercontent.com/75069381/110656890-aa8cf300-81c0-11eb-8ee9-37d72f51d4aa.png)

The output:
![image](https://user-images.githubusercontent.com/75069381/110656948-baa4d280-81c0-11eb-9f6d-2ed86ccde92d.png)

**Comment by sarahmish** [comment]
Closing this since the question has been answered by @dyuliu!

@GiacomoSintoni if you have further questions or details, feel free to reopen this issue :)

**Comment by Dylanlalala** [comment]
i have the same question
