### ISSUE TITLE
Some error on the colab notebook (Contextual Version Confilct)

### ISSUE THREAD

**Issue by TylerChoi1224** [signals-dev/Orion#215]
* Orion version : 0.1.7
* Python version : 3.7.10
* Operating System : Windows 10

### Description
I am trying to execute Quickstart of your github in my colab environment.
But I have some problem below.

Please check this problem and hope you help me. 
Thank you.

### What I Did
At first, I did "pip install orion-ml", and then did restart runtime.

![image](https://user-images.githubusercontent.com/74239291/111751215-90959380-88d7-11eb-9d5c-99aa1654d650.png)

![image](https://user-images.githubusercontent.com/74239291/111751258-9ee3af80-88d7-11eb-8b63-5c705f017c59.png)

![image](https://user-images.githubusercontent.com/74239291/111751151-78be0f80-88d7-11eb-85b0-ec1c3838322a.png)

**Comment by sarahmish** [comment]
Hi @TylerChoi1224, can you paste the entire error output?

For now, include `pip install 'urllib3>=1.25.4,<1.26'` in addition when installing orion. 

**Note to myself:** update setup to resolve version conflict

https://github.com/signals-dev/Orion/blob/8febfbddf6713936a95adae435a905edad7f786b/setup.py#L37

**Comment by sarahmish** [comment]
Updated `setup.py` req to reflect this change PR #223.
In addition, changes have been made to the colab notebook.
