### ISSUE TITLE
How to import hyperparameters from module.py?

### ISSUE THREAD

**Issue by FranVV-Ecu** [signals-dev/Orion#220]
* Orion version:0.1.6
* Python version: 3.7.10
* Operating System: Windows 10(Google Colab)

### Description

I'm trying to generate data from my time series that is not continuous. I'm going trough your tutorial at medium and trying to use TadGan, but I'm not able to find module.py in orfet to import hyperparameters. Could you please can recommend me what can i Do?

### What I Did
![image](https://user-images.githubusercontent.com/60336954/112728659-65472000-8f39-11eb-865f-fb7290d09a16.png)

```
from model import hyperparameters



```

**Comment by sarahmish** [comment]
Hi @FranVV-Ecu, you can visit the latest [notebook](https://colab.research.google.com/drive/1TVNK6HroahDeFFl06oOFYISt5JLLSSLO?usp=sharing) for convenience.

simply run the following block to download relevant functionalities.
```
! git clone https://github.com/signals-dev/Orion.git
! mv Orion/notebooks/tulog/* .
```
