### ISSUE TITLE
Rolling windows sequence function?

### ISSUE THREAD

**Issue by FranVV-Ecu** [signals-dev/Orion#222]
* Orion version: 0.1.6
* Python version: 3.7.10
* Operating System: Windows 10

### Description

When I apply time function rolling window sequence take a too long time? My time series index is np.datatime64 and the interval of function is not seconds when the function is applied.

### What I Did

```
Redifine inteval parameter to : 

interval = np.timedelta64(interval, 's')
```

**Comment by sarahmish** [comment]
Hi @FranVV-Ecu, can you provide more detail? What does the input look like? It would be helpful for me to see what code you ran and causes this problem.

The `rolling_window_sequence` primitive would talk a long time if the signal is long and the `interval` set is small. However, it still should be relatively fast.
