### ISSUE TITLE
How to use Orion on personal dataset ??

### ISSUE THREAD

**Issue by RaunakKumarVerma** [signals-dev/Orion#224]
* Orion version:
* Python version: 3.7.10
* Operating System:Microsoft Windows 10 version 20H2( OS Build 19042.746)

### Description

Describe what you were trying to get done.

I tried running this code on the pump sensors dataset with 2 columns i.e. timestamp and value. I have added the sample dataset for reference.
	timestamp	value
0	104000000	2.465394
1	104000100	2.465394
2	104000200	2.444734
3	104000300	2.460474
4	104000400	2.445718

Tell us what happened, what went wrong, and what you expected to happen.
 the function load anomalies refer to a set of predefined datasets listed in the anomalies.csv file. How can I implement it on a dataset which is not in that CSV file? 
### What I Did

# load signal
df = pd.read_csv('sensor.csv')

# load ground truth anomalies
known_anomalies = load_anomalies('sensor.csv')

df.head(5)

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
                                   signal  \
0                                     P-1   
1                                     S-1   
2                                     E-1   
3                                     E-2   
4                                     E-3   
5                                     E-4   
6                                     E-5   
7                                     E-6   
8                                     E-7   
9                                     E-8   
10                                    E-9   
11                                   E-10   
12                                   E-11   
13                                   E-12   
14                                   E-13   
15                                    A-1   
16                                    D-1   
17                                    P-2   
18                                    P-3   
19                                    D-2   
20                                    D-3   
21                                    D-4   
22                                    A-2   
23                                    A-3   
24                                    A-4   
25                                    G-1   
26                                    G-2   
27                                    D-5   
28                                    D-6   
29                                    D-7   
..                                    ...   
105                exchange-2_cpc_results   
106                exchange-2_cpm_results   
107                exchange-3_cpc_results   
108                exchange-3_cpm_results   
109                exchange-4_cpc_results   
110                exchange-4_cpm_results   
111    ambient_temperature_system_failure   
112  cpu_utilization_asg_misconfiguration   
113    ec2_request_latency_system_failure   
114    machine_temperature_system_failure   
115                              nyc_taxi   
116                  rogue_agent_key_hold   
117                rogue_agent_key_updown   
118                        TravelTime_387   
119                        TravelTime_451   
120                        occupancy_6005   
121                       occupancy_t4013   
122                            speed_6005   
123                            speed_7578   
124                           speed_t4013   
125                   Twitter_volume_AAPL   
126                   Twitter_volume_AMZN   
127                    Twitter_volume_CRM   
128                    Twitter_volume_CVS   
129                     Twitter_volume_FB   
130                   Twitter_volume_GOOG   
131                    Twitter_volume_IBM   
132                     Twitter_volume_KO   
133                    Twitter_volume_PFE   
134                    Twitter_volume_UPS   

                                                events  
0    [[1331272800, 1335592800], [1382832000, 138948...  
1                           [[1398168000, 1407823200]]  
2    [[1393027200, 1393675200], [1406203200, 141648...  
3                           [[1405944000, 1436119200]]  
4                           [[1395057600, 1465905600]]  
5                           [[1402747200, 1463464800]]  
6                           [[1405987200, 1412899200]]  
7                           [[1406203200, 1407607200]]  
8                           [[1399140000, 1405188000]]  
9                           [[1401667200, 1415102400]]  
10                          [[1404907200, 1412467200]]  
11   [[1393027200, 1394107200], [1406008800, 141184...  
12   [[1393027200, 1394107200], [1406289600, 141153...  
13   [[1406203200, 1417672800], [1393027200, 139410...  
14   [[1399701600, 1401883200], [1405987200, 140685...  
15                          [[1386331200, 1388145600]]  
16                          [[1397757600, 1470009600]]  
17                          [[1399312800, 1425772800]]  
18                          [[1401148800, 1429984800]]  
19                          [[1378317600, 1469404800]]  
20                          [[1397887200, 1468627200]]  
21                          [[1396872000, 1467612000]]  
22                          [[1376136000, 1378512000]]  
23                          [[1380736800, 1384732800]]  
24                          [[1379203200, 1381579200]]  
25                          [[1386763200, 1389355200]]  
26                          [[1363392000, 1364256000]]  
27                          [[1381816800, 1382896800]]  
28                          [[1384041600, 1385769600]]  
29                          [[1385316000, 1443852000]]  
..                                                 ...  
105                          [[1310349601,1310932801]]  
106  [[1311508801,1311796801],[1312840801,1313132401]]  
107  [[1310541301,1310721301],[1311059701,131123970...  
108                          [[1313482501,1314051301]]  
109  [[1310703301,1310897701],[1312175701,131237730...  
110  [[1310728501,1310872501],[1312103701,131225490...  
111  [[1387087200,1388390400],[1396101600,1398024000]]  
112                          [[1404988140,1405437540]]  
113  [[1394764260,1394804460],[1395158760,139519896...  
114  [[1386653100,1386822900],[1387126200,138729600...  
115  [[1414679400,1415050200],[1416913200,141728400...  
116  [[1405391700,1405423500],[1405569000,1405658700]]  
117  [[1405350000,1405429200],[1405540200,1405619400]]  
118  [[1437987360,1438358460],[1439805060,144002844...  
119                          [[1439135820,1439402460]]  
120                          [[1442245500,1442330640]]  
121  [[1442357940,1442402340],[1442442000,1442488200]]  
122                          [[1442421600,1442499840]]  
123  [[1441978440,1441986840],[1442316360,144232524...  
124  [[1442357040,1442402040],[1442442600,1442489400]]  
125  [[1425353873,1425472673],[1425859373,142597817...  
126  [[1425522173,1425640373],[1426044773,142616297...  
127  [[1425844973,1426003973],[1426723373,142688237...  
128  [[1425421973,1425641273],[1427315873,142743467...  
129  [[1426367573,1426604573],[1427957573,1428194573]]  
130  [[1426215173,1426406273],[1427001773,142712057...  
131  [[1427026973,1427265173],[1429434173,1429672373]]  
132  [[1426774373,1426932773],[1428450173,142860857...  
133  [[1425268373,1425387173],[1425402173,142552097...  
134  [[1425291473,1425386273],[1425416273,142551107...  

[135 rows x 2 columns]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\.conda\envs\orion\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2656             try:
-> 2657                 return self._engine.get_loc(key)
   2658             except KeyError:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine._get_loc_duplicates()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine._maybe_get_bool_indexer()

KeyError: 'sensor.csv'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-12-e1afae19a87a> in <module>
      5 
      6 # load ground truth anomalies
----> 7 known_anomalies = load_anomalies('sensor.csv')
      8 
      9 df.head(5)

~\Downloads\Orion-master\Orion-master\notebooks\tulog\data.py in load_anomalies(signal, edges)
    143    # anomalies = download('anomalies')
    144     print(anomalies)
--> 145     anomalies = anomalies.set_index('signal').loc[signal].values[0]
    146     print(anomalies)
    147     anomalies = pd.DataFrame(json.loads(anomalies), columns=['start', 'end'])

~\.conda\envs\orion\lib\site-packages\pandas\core\indexing.py in __getitem__(self, key)
   1498 
   1499             maybe_callable = com.apply_if_callable(key, self.obj)
-> 1500             return self._getitem_axis(maybe_callable, axis=axis)
   1501 
   1502     def _is_scalar_access(self, key):

~\.conda\envs\orion\lib\site-packages\pandas\core\indexing.py in _getitem_axis(self, key, axis)
   1911         # fall thru to straight lookup
   1912         self._validate_key(key, axis)
-> 1913         return self._get_label(key, axis=axis)
   1914 
   1915 

~\.conda\envs\orion\lib\site-packages\pandas\core\indexing.py in _get_label(self, label, axis)
    139             raise IndexingError('no slices here, handle elsewhere')
    140 
--> 141         return self.obj._xs(label, axis=axis)
    142 
    143     def _get_loc(self, key, axis=None):

~\.conda\envs\orion\lib\site-packages\pandas\core\generic.py in xs(self, key, axis, level, drop_level)
   3583                                                       drop_level=drop_level)
   3584         else:
-> 3585             loc = self.index.get_loc(key)
   3586 
   3587             if isinstance(loc, np.ndarray):

~\.conda\envs\orion\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2657                 return self._engine.get_loc(key)
   2658             except KeyError:
-> 2659                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2660         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   2661         if indexer.ndim > 1 or indexer.size > 1:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine._get_loc_duplicates()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine._maybe_get_bool_indexer()

KeyError: 'sensor.csv'

**Comment by sarahmish** [comment]
hi @RaunakKumarVerma, the error your showing is because you attempted to use `load_anomalies` function on your own dataset. This function has been implemented to load ground truth data from online sources. To run Orion, simply proceed without calling it

```python3
df = load_signal('sensors.csv')

hyperparameters = {
    'mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1': {
        'intervals': 100
    },
    'keras.Sequential.LSTMTimeSeriesRegressor#1': {
        'epochs': 5,
        'verbose': True
    }
}

orion = Orion(
    pipeline='lstm_dynamic_threshold',
    hyperparameters=hyperparameters
)

orion.fit(df)
```

**Comment by RaunakKumarVerma** [comment]
hi @sarahmish , thanks for helping.  I tried the solution you provided but it still ran into a problem.

The code I tried was 


df = load_signal('sensor.csv')

from orion import Orion

hyperparameters = {
    'mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1': {
        'intervals': 100
    },
    'keras.Sequential.LSTMTimeSeriesRegressor#1': {
        'epochs': 5,
        'verbose': True
    }
}

orion = Orion(
    pipeline='lstm_dynamic_threshold',
    hyperparameters=hyperparameters
)

orion.fit(df)

And the error that I am getting is

Using TensorFlow backend.
Exception caught producing MLBlock mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1
Traceback (most recent call last):
  File "C:\Users\Raunak\.conda\envs\orion\lib\site-packages\mlblocks\mlpipeline.py", line 565, in _produce_block
    block_outputs = block.produce(**produce_args)
  File "C:\Users\Raunak\.conda\envs\orion\lib\site-packages\mlblocks\mlblock.py", line 325, in produce
    return self.primitive(**produce_kwargs)
TypeError: time_segments_aggregate() got an unexpected keyword argument 'intervals'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-cb3494bc2871> in <module>
     16 )
     17 
---> 18 orion.fit(df)

~\.conda\envs\orion\lib\site-packages\orion\core.py in fit(self, data)
     82         """
     83         self._mlpipeline = self._get_mlpipeline()
---> 84         self._mlpipeline.fit(data)
     85         self._fitted = True
     86 

~\.conda\envs\orion\lib\site-packages\mlblocks\mlpipeline.py in fit(self, X, y, output_, start_, **kwargs)
    650 
    651             if (block_name != self._last_block_name) or (block_name in output_blocks):
--> 652                 self._produce_block(block, block_name, context, output_variables, outputs)
    653 
    654                 # We already captured the output from this block

~\.conda\envs\orion\lib\site-packages\mlblocks\mlpipeline.py in _produce_block(self, block, block_name, context, output_variables, outputs)
    563         try:
    564             produce_args = self._get_block_args(block_name, block.produce_args, context)
--> 565             block_outputs = block.produce(**produce_args)
    566 
    567             outputs_dict = self._extract_outputs(block_name, block_outputs, block.produce_output)

~\.conda\envs\orion\lib\site-packages\mlblocks\mlblock.py in produce(self, **kwargs)
    323 
    324         produce_kwargs.update(self.get_hyperparameters())
--> 325         return self.primitive(**produce_kwargs)

TypeError: time_segments_aggregate() got an unexpected keyword argument 'intervals'


How can I resolve this??

**Comment by sarahmish** [comment]
Apologies from my side, I had a type in the hyperparameter configuration and wrote `intervals` instead of `interval` (fixed the above snippet). You can double check the naming of hyperparameters by visiting the documentation page of the respective [primitive](https://signals-dev.github.io/Orion/user_guides/primitives_pipelines/primitives/time_segments_aggregate.html).

Try it again and let me know if any further issues arise.

**Comment by sarahmish** [comment]
Closing since the issue was answered.
