### ISSUE TITLE
Identifying other datasets that have similar behavior

### ISSUE THREAD

**Issue by jgubner** [signals-dev/Orion#228]
* Orion version:
* Python version:
* Operating System:

### Description

I have 12 data files from similar attitude determination and control system (ADCS) components that should behave similarly. If I give Orion one of those 12 files and then a set of, say 50, files including the other 11 of interest, would Orion be able to identify those other 11 files out of the whole set? How would I go about doing this?

**Comment by sarahmish** [comment]
Hi @jgubner

I am not sure I understand the question properly. If you identify anomalies in 1 file (i.e. one signal) would it be able to detect anomalies in all the remaining signals without re-training the model?

Would you kindly elaborate more such that I understand the problem better.

**Comment by jgubner** [comment]
Absolutely, @sarahmish! Sorry for the lack of clarity.

What I mean is:

Say I have a folder full of 50 different data files from different spacecraft components. Within that folder, there are 12 files that all come from sun sensors (each of those 12 files records counts over time on each of the sun sensor diodes), but each sun sensor is located in a slightly different location across the spacecraft. If I were to point Orion to one of those 12 files and say "this is a sun sensor file", is it possible to have Orion locate the other 11 sun sensor files out of the 50 based on feature similarities, scale, or some other metric?

Does this make sense or is it still unclear?

**Comment by sarahmish** [comment]
I see @jgubner.

I think the idea here is to kind of "match" a file — sun sensor file — between different directories based on the properties/features of the signal correct?

If so I think this is out of scope for Orion, our main objective is to take a signal as input and produce anomalies as output.

Let me know if I understood the question correctly and if my answer makes sense to you!

**Comment by jgubner** [comment]
@sarahmish , yeah. The idea is to be able to load in different datasets and be able to group them appropriately based on features, mean levels, or some other metrics.

I understand this is out of scope. Thanks for the reply!
