### ISSUE TITLE
Where can I find Univariate Time-series data for fault detection in machinery?

### ISSUE THREAD

**Issue by RaunakKumarVerma** [signals-dev/Orion#230]
I am working on a project with Generative Adversarial Network to generate pseudo (minority) samples to expand the dataset and then using that expanded dataset to train my model for fault detection in machinery.
I have already tried my project with 2 machine temperature sensor datasets (containing timestamp and temperature data at that timestamp).
I am looking for a dataset having a similar structure (i.e timestamp with one sensor data) , For Example, Current sensor with time or pressure sensor with time. 

I have searched Kaggle but most datasets on Kaggle are multivariate. 
Where can I find Univariate Time-series data for fault detection in machinery?

**Comment by sarahmish** [comment]
Hi @RaunakKumarVerma,

Maybe checkout [Numenta's NAB repo](https://github.com/numenta/NAB/tree/master/data) with similar datasets? Maybe you can find something relevant there.
