### ISSUE TITLE
finding known anomalies from NAB

### ISSUE THREAD

**Issue by salman087** [signals-dev/Orion#235]
I am confused about how the known anomalies are obtained for NAB datasets. From the nab repository only single points are considered anomaly then how can we convert this into the interval. Can you please provide a sample code for this?

**Comment by sarahmish** [comment]
hi @salman087, the known anomalies are obtained directly from the [original source](https://github.com/numenta/NAB/blob/master/labels/combined_windows.json), they are defined in interval based structure as well, the only transformation we applied is convert it into a `timestamp` format.

let me know if you have any further questions.

**Comment by salman087** [comment]
Thank you for your reply. I am not clear about how a single timestamp is converted into an interval. For example, there are 5 anomalies at different locations in the nyc-taxi dataset(according to the original source). So my question is how these single points(known_anomalies) are converted into 5 different intervals.  Is it the whole day is considered anomalous or something else. ?

**Comment by sarahmish** [comment]
If you visit the link of the [original source](https://github.com/numenta/NAB/blob/master/labels/combined_windows.json), it is defined in intervals. 
Here's the nyc-taxi dataset you are referring to:
```
    "realKnownCause/nyc_taxi.csv": [
        [
            "2014-10-30 15:30:00.000000",
            "2014-11-03 22:30:00.000000"
        ],
        [
            "2014-11-25 12:00:00.000000",
            "2014-11-29 19:00:00.000000"
        ],
        [
            "2014-12-23 11:30:00.000000",
            "2014-12-27 18:30:00.000000"
        ],
        [
            "2014-12-29 21:30:00.000000",
            "2015-01-03 04:30:00.000000"
        ],
        [
            "2015-01-24 20:30:00.000000",
            "2015-01-29 03:30:00.000000"
        ]
    ],
```

**Comment by kanesp** [comment]
if i want to Make  label on  the nyc-taxi dataset, every timestamp in the anomaly (intervals) need be labeled anomalous ？
e.g., in [ "2014-10-30 15:30:00.000000", "2014-11-03 22:30:00.000000" ] , 2014-10-30 16:00 and 2014-10-30 16:30 are all anomolous. 
thanks for ur reply.

**Comment by salman087** [comment]
As per my understanding, Yes, all points that lie in the interval are labelled as anomalous.

**Comment by kanesp** [comment]
yes, i think too. i am making labels for NASA datasets.  But i feel confused about the anomalies.  In the 'orion/data/anomalies.csv' , i find A-8,"[[1337968800, 1425556800]]".  But!!!!! I used ' the notebooks/Convert NASA data to Orion format.ipynb' to conver NASA datasets, then i find  i cannot find the timestamp(1425556800)  in A-8 . At the same time, the max timestamp is 
1420156800.  @salman087 @sarahmish  I don't know whether i am right.

**Comment by sarahmish** [comment]
Hi @kanesp! Yes you are right, you should be able to convert the anomalies in the NASA dataset

which is ``[[1337968800, 1420156800]]`` for A-8. I will investigate this further and mark it as an issue for the anomalies saved in `orion/data`. Thank you for pointing it out!
