### ISSUE TITLE
Why use anomaly padding ? 

### ISSUE THREAD

**Issue by kronerte** [signals-dev/Orion#236]
* Orion version: 0.1.6
* Python version: 3.7.10
* Operating System: Windows 10

### Description

On https://github.com/signals-dev/Orion/blob/master/orion/primitives/timeseries_anomalies.py
the function :

```
def find_anomalies(errors, index, z_range=(0, 10), window_size=None, window_size_portion=None,
                   window_step_size=None, window_step_size_portion=None, min_percent=0.1,
                   anomaly_padding=50, lower_threshold=False, fixed_threshold=None):
```

We have a parameter "anomaly_padding" who had detected anomalies before and after previously detected anomalies. 
I do not understand the purpose of this parameter. 
Why use anomaly padding ? Are there any theoretical justifications ? 
Is it to reduce false negatives ?

**Comment by sarahmish** [comment]
hey @kronerte, thank you for your question.

the parameter `anomaly_padding` indicates the number of errors before and after a discovered anomaly that are added to the anomalous sequence. the intuition behind this parameter is to merge nearby anomalous sequences together. the implementation of some of these functions are inspired by the paper [nasa paper](https://arxiv.org/pdf/1802.04431.pdf) on anomaly detection.

let me know if this answers your question!

**Comment by kronerte** [comment]
Okay, yes that respond to my question. 
Thank you.
