### ISSUE TITLE
How to compute the F1 score over a dataset?

### ISSUE THREAD

**Issue by kanesp** [signals-dev/Orion#238]
* Orion version: 0.1.7
* Python version:3.6
* Operating System:Ubuntu 18.04.5 LTS

### Description

In NAB dataset for Art, it has 6 signals. how to compute the F1 score for Art? 
 I cannot find the concrete descriptions for the computation of F1 in Orion.
I use the mean F1 socre.

### What I Did
I have used the Tadgan pipeline to detect the NAB(art) and got the 6 signals' F1 scores for NAB(art), how to compute the Art F1 score overall?  
```
#score_art_daily_flatmiddle.csv
F1 = 1
#score_art_daily_jumpsdown.csv
F1 = 1
#score_art_daily_jumpsup.csv
F1 = 1
#score_art_daily_nojump.csv
F1 = 1
#score_art_increase_spike_density.csv
F1 = 0.666667
#art_load_balancer_spikes.csv
F1 = 0.5
```
### The mean F1 score for Art 
I use the mean of the SIX  F1 scores. 
```
0.86
```

**Comment by dyuliu** [comment]
Hi @kanesp, this is a good question. Here is how we compute the F1 score over a dataset (e.g., Art):

We don't use the mean of the F1 score for each signal; instead, we maintain four variables `sum_tp`, `sum_tn`, `sum_fp`, and `sum_fn` to record the total number of tp, tn, fp, and fn for all the signals – in your case should be the SIX signals in Art dataset.

Calculate precision/recall/f1 score individually and then use mean of them may suffer from the following problem:
- the number of anomalies in different signals can be very different; some may contain many while some may contain only few and even zero. So they are very unbalanced and simply using mean can lose such information;
- tp, fp, and fn for the individual signal can be often zero, leading to `None` value for precision/recall/f1. In this case, it's hard to decide whether we should count it in the computation of mean.

**Comment by kanesp** [comment]
thank u! i find the tp, tn, fp, and fn are computed in `orion/evaluation/contextual.py`with the function `contextual_confusion_matrix`.   Is it used to compute the  tp, tn, fp, and fn?  At the same time , in  the function `contextual_confusion_matrix`,  `expected`is the ground truth, `observed ` is the detected anomalies, but what is  the `data`?  is the whole dataset (like `nyc_taxi.csv`)?

**Comment by sarahmish** [comment]
@kanesp the `data` is the timeseries, it is an optional argument used to extract the `start` and `end` of the timeseries. If you do not provide it, we extract it from `observed` and `expected`.
