### ISSUE TITLE
Return the generated time series from TadGAN pipeline 

### ISSUE THREAD

**Issue by techfreckels** [signals-dev/Orion#239]
Is there a way, after training the tgan model to return the generator of the series without anomalies? I'd like to sample the distribution.

**Comment by sarahmish** [comment]
hi @techfreckels, based on my understanding of the question, you would like to have the generated time series from the TadGAN model. This can be accomplished using the `visualization` option in Orion.

A simple example can be see here
```python3
from orion.data import load_signal
from orion import Orion

signal = load_signal('S-1') 
hyper = {
    "orion.primitives.tadgan.TadGAN#1": {
        "epochs": 5
    }
} 
orion = Orion("tadgan_viz", hyper)
orion.fit(signal) 

anomalies, viz = orion.detect(signal, visualization=True)
```

the variable `viz` now is a dictionary with all the items you specified in the pipeline `tadgan_viz` that you want to have as output (one of which is `generated_timeseries`). You can add more to this list by specifying which primitive and which variable you want in your output.

Let me know if you have any further question!
