### ISSUE TITLE
no module mlblocks

### ISSUE THREAD

**Issue by husnejahan** [signals-dev/Orion#245]
* Orion version:
* Python version:
* Operating System:

### Description

when running Tulog.ipynb I am getting import error, there is no module mlblocks.

### What I Did

```
13 import pandas as pd
---> 14 from mlblocks import MLPipeline
     15 
     16 from orion.evaluation import CONTEXTUAL_METRICS as METRICS

ModuleNotFoundError: No module named 'mlblocks'

```

**Comment by sarahmish** [comment]
Hi @husnejahan, it seems like `Orion` is not installed.

You can try to run `!pip install orion-ml` in the first cell of your notebook to install it.

**Comment by MlLearnerAkash** [comment]
![image](https://github.com/sintel-dev/Orion/assets/81233167/a0a8177b-9211-4dd1-8775-291073b9577e)
Although, my orion-ml package is installed, its still can't import mlblocks.
@Author, can you put some light on this topic
