### ISSUE TITLE
multivariate TadGAN

### ISSUE THREAD

**Issue by ohyj9912** [signals-dev/Orion#250]
* Orion version: 
* Python version: 3.6
* Operating System: jupyter notebook (centos7)

### Description
I try to apply tadgan to multivariate personal data.(3-variables, 1 timestamp)
(image is part of data)
![image](https://user-images.githubusercontent.com/54938390/135406347-53181eba-6e75-46ea-82fc-391ddd5452a3.png)

### What I Did
```
from orion import Orion

parameters = {
    "mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1": {
            "interval": 1
        },
    
    'orion.primitives.tadgan.TadGAN#1': {
        'epochs': 5,
        'input_shape': [100, 3], # where 100 is the window size and 3 is the number of channels 
        'verbose': True 
        },
}

orion = Orion(
    'tadgan',
    parameters
)
```

### Output

![image](https://user-images.githubusercontent.com/54938390/135406050-45f08110-4470-4b79-bc24-5b98fe61975c.png)
![image](https://user-images.githubusercontent.com/54938390/135406084-42c4c605-cfff-4eba-82e8-b70d252bdd90.png)

there's error
what should i do? plz help

**Comment by sarahmish** [comment]
Hi @ohyj9912, the feature is still under development, please follow PR #249 to know when it has been merged.

**Comment by ohyj9912** [comment]
thanks!!!
